CREATE TABLE IF NOT EXISTS `carinfo`(
    `id` INT PRIMARY KEY AUTO_INCREMENT, 
    `carid` VARCHAR(32) PRIMARY KEY, `carinfo` VARCHAR(512), 
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);